// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comparisons struct {
	ComparisonID    int32            `json:"comparison_id"`
	UserID          int32            `json:"user_id"`
	BaseMovieID     int32            `json:"base_movie_id"`
	ComparedMovieID int32            `json:"compared_movie_id"`
	Preference      int16            `json:"preference"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Genres struct {
	GenreID int32  `json:"genre_id"`
	Name    string `json:"name"`
}

type MovieAvailability struct {
	MovieID   int32 `json:"movie_id"`
	ServiceID int32 `json:"service_id"`
}

type MovieCacheLog struct {
	TmdbID      int32            `json:"tmdb_id"`
	LastFetched pgtype.Timestamp `json:"last_fetched"`
}

type MovieGenres struct {
	MovieID int32 `json:"movie_id"`
	GenreID int32 `json:"genre_id"`
}

type MoviePeople struct {
	MovieID  int32  `json:"movie_id"`
	PersonID int32  `json:"person_id"`
	Role     string `json:"role"`
}

type Movies struct {
	MovieID        int32            `json:"movie_id"`
	TmdbID         int32            `json:"tmdb_id"`
	ImdbID         pgtype.Text      `json:"imdb_id"`
	Title          string           `json:"title"`
	Overview       pgtype.Text      `json:"overview"`
	ReleaseDate    pgtype.Date      `json:"release_date"`
	PosterPath     pgtype.Text      `json:"poster_path"`
	BackdropPath   pgtype.Text      `json:"backdrop_path"`
	TmdbPopularity pgtype.Numeric   `json:"tmdb_popularity"`
	LastUpdated    pgtype.Timestamp `json:"last_updated"`
}

type People struct {
	PersonID           int32          `json:"person_id"`
	TmdbID             int32          `json:"tmdb_id"`
	Name               string         `json:"name"`
	KnownForDepartment pgtype.Text    `json:"known_for_department"`
	Biography          pgtype.Text    `json:"biography"`
	Birthday           pgtype.Date    `json:"birthday"`
	Deathday           pgtype.Date    `json:"deathday"`
	Gender             pgtype.Int2    `json:"gender"`
	ProfilePath        pgtype.Text    `json:"profile_path"`
	TmdbPopularity     pgtype.Numeric `json:"tmdb_popularity"`
}

type Ratings struct {
	RatingID    int32            `json:"rating_id"`
	UserID      int32            `json:"user_id"`
	MovieID     int32            `json:"movie_id"`
	RatingScore pgtype.Numeric   `json:"rating_score"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}

type StreamingServices struct {
	ServiceID int32       `json:"service_id"`
	Name      string      `json:"name"`
	LogoPath  pgtype.Text `json:"logo_path"`
}

type UserMovies struct {
	UserID    int32            `json:"user_id"`
	MovieID   int32            `json:"movie_id"`
	Rating    pgtype.Numeric   `json:"rating"`
	Review    pgtype.Text      `json:"review"`
	Watchlist pgtype.Bool      `json:"watchlist"`
	Watched   pgtype.Bool      `json:"watched"`
	Favorited pgtype.Bool      `json:"favorited"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Users struct {
	UserID       int32            `json:"user_id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
